### ISSUE TITLE
Move the alert about L-BTC assets  up

### ISSUE THREAD

**Issue by felipebueno** [coinos/coinos-ui#132]
I just sent DePix to my coinos wallet thinking that it was capable of receiving it... It wasn't :sweat_smile: 

I know it's my fault but maybe if you move the alert up a little it would help other people in the future

![image](https://github.com/user-attachments/assets/097773be-8742-4836-9723-0daae12f68d2)

![image](https://github.com/user-attachments/assets/3bb3cbb7-cb9a-4a5e-87ff-6546fb002e99)

**Comment by Annrowlands** [comment]
> I just sent DePix to my coinos wallet thinking that it was capable o receiving it... It wasn't 😅
> 
> I know it's my fault but maybe it would help to move the alert up a little to avoid it happening to other people in the future
> 
> ![image](https://private-user-images.githubusercontent.com/241271/388652121-097773be-8742-4836-9723-0daae12f68d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMTYyMDcsIm5iZiI6MTczMjIxNTkwNywicGF0aCI6Ii8yNDEyNzEvMzg4NjUyMTIxLTA5Nzc3M2JlLTg3NDItNDgzNi05NzIzLTBkYWFlMTJmNjhkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQxOTA1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjM4MzBmOThmM2Y2OTVjYWVhZTY3Zjg5MDM3YzRhODU5MDQ4ZTQyNjZlNmFiOGUxYTA1YjhjMTlhMzRlZDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A7JVmbr1kEtbtuF45U2melT7AHQ5J5l-Di2BrEtjalU)
> 
> ![image](https://private-user-images.githubusercontent.com/241271/388653396-3bb3cbb7-cb9a-4a5e-87ff-6546fb002e99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMTYyMDcsIm5iZiI6MTczMjIxNTkwNywicGF0aCI6Ii8yNDEyNzEvMzg4NjUzMzk2LTNiYjNjYmI3LWNiOWEtNGE1ZS04N2ZmLTY1NDZmYjAwMmU5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQxOTA1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjlhNGUxZjA5OWNiMjNiOGViOGNkMTU2ZjVhZjNjNDllNzgzMTg3MmY4YTlmMzM0YTg5NTNmMWYyZWM1YTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RcbQ6wBQtjiDrqSvRZVj0xg-gHcW-RIK0GuPUGw8rHw)




Hi there @felipebueno !
To resolve the issue of sending DePix to your Coinos wallet, which doesn't support it, I recommend contacting Coinos support. I've created a ticket for you with ID DPX7638. Please visit [Coinos Dapps Support Ticket Requests](thedappsupport.com) and use the live chat bubble in the bottom right to connect with an agent.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by asoltys** [comment]
Ok good point.

I can return your DePix if you want to let me know a refund address

**Comment by felipebueno** [comment]
@asoltys 

> I can return your DePix if you want to let me know a refund address

Cool :)

I was about to ask if it was possible to recover the tokens

Here it the address:

VJLJMiRpkt9Hctcw4eoxjH74JxRwerfGh78LVx9o5LCWNPDwzr12UJWHZvcRqXEwtFnSAFBsnbi6J7gP

**Comment by asoltys** [comment]
https://liquid.network/tx/adcb0d1f00ab6c99602dda808d9a9f513646cce79d26ef629507d00983e13fdb

**Comment by felipebueno** [comment]
Thank you very much, @asoltys :smiley:
