### ISSUE TITLE
PoS mode

### ISSUE THREAD

**Issue by jooray** [coinos/coinos-ui#15]
It would be great to be able to create a "receive only" instance of a wallet.

For example coffee shop operator has their wallet in receive and send mode. But they can share a special URL for a xpub-only / lightning-receive-only wallet. So customers can pay at the counter using BTC/L-BTC/lightning, but only the store owner can send out the balance.

**Comment by asoltys** [comment]
Yeah it's a good idea I've had that in mind for a while too. As a workaround for now you can set a PIN code on the account. It should prompt for the PIN when sending outgoing payments so just don't tell it to your staff..

**Comment by asoltys** [comment]
We have a public page for every user now e.g. https://coinos.io/adam which is read-only
