### ISSUE TITLE
Cannot run locally

### ISSUE THREAD

**Issue by bensig** [coinos/coinos-ui#21]
Tried to run this locally and I got the following error:

```
Proxy error: Could not proxy request /assets from localhost:8085 to http://app:3119.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

```

I tried changing `http://app` to `http://localhost` and I got the same error but for http://localhost

Did I miss something in the docs?

**Comment by drschwabe** [comment]
Hi bensig, the docs on this repo are a tad dated.  I have just recently forked (and PR'ed) a README update to coinos-server repo with updated instructions which when followed should at least get you passed this point; fixes your proxy issue here:  

https://github.com/drschwabe/coinos-server

(note coinos-ui is standalone repo here but is actually cloned and auto-started apart of the updated coinos-server docker technique)
