### ISSUE TITLE
QR Code or Option to Display on public page.

### ISSUE THREAD

**Issue by HamishMacEwan** [coinos/coinos-ui#23]
Hi,

https://coinos.io/032e8ec5-lntxbot

Be useful to have a QR code displayed, or the option to along with the LNURL string.

**Comment by ahopk127** [comment]
Hi,

If you press "Checkout", you should get a QR code.  See the below screenshot:
![Screenshot 2021-08-19 093437](https://user-images.githubusercontent.com/73263261/130077855-126dfce4-f96d-408e-a276-0b50cd41c0e0.png)

**Comment by HamishMacEwan** [comment]
I do get a QR code, but it's not exactly intuitive or expected.  Perhaps a QR code icon rather than "Checkout?"
